package langs

const goEmptyPackage = `// WARNING: Automatically generated by ludco. DO NOT EDIT.

package {{.pkg}}

type {{.name}} struct{}
func (t {{.name}}) LudwiegID() byte { return {{.id}} }
func (t {{.name}}) LudwiegMeta() []LudwiegTypeAnnotation { return []LudwiegTypeAnnotation{} }
`

const goField = "	{{.name}} {{.type}}\n"

const goPackage = `// WARNING: Automatically generated by ludco. DO NOT EDIT.

package {{.pkg}}

type {{.name}} struct {
{{.fields}}
}

func (t {{.name}}) LudwiegID() byte { return {{.id}} }
func (t {{.name}}) LudwiegMeta() []LudwiegTypeAnnotation { return []LudwiegTypeAnnotation{ {{.annotations}} } }

{{.structures}}
`

const goStruct = `
type {{.name}} struct {
{{.fields}}
}

func (t {{.name}}) LudwiegMeta() []LudwiegTypeAnnotation { return []LudwiegTypeAnnotation{ {{.annotations}} } }

{{.structures}}
`

const goInitializer = `// WARNING: Automatically generated by ludco. DO NOT EDIT.

package {{.pkg}}

func init() {
	RegisterPackages({{.packages}})
}
`
