package langs

const objcEmptyPackageHeader = `// WARNING: Automatically generated by ludco. DO NOT EDIT.
#import <Foundation/Foundation.h>
#import <Ludwieg/Ludwieg.h>

@interface {{.prefix}}{{.name}} : NSObject <LUDSerializablePackage>
@end
`

const objcEmptyPackageImplementation = `// WARNING: Automatically generated by ludco. DO NOT EDIT.
#import "{{.prefix}}{{.name}}.h"

@implementation {{.prefix}}{{.name}}

+ (uint8_t)ludwiegID { return {{.id}}; }
+ (NSArray<LUDTypeAnnotation *> *)ludwiegMeta { return @[]; }

@end
`

const objcPackageHeader = `// WARNING: Automatically generated by ludco. DO NOT EDIT.
#import <Foundation/Foundation.h>
#import <Ludwieg/Ludwieg.h>
{{.structures}}

@interface {{.prefix}}{{.name}} : NSObject <LUDSerializablePackage>

{{.fields}}
@end
`

const objcPackageImplementation = `// WARNING: Automatically generated by ludco. DO NOT EDIT.
#import "{{.prefix}}{{.name}}.h"

@implementation {{.prefix}}{{.name}}

+ (uint8_t)ludwiegID { return {{.id}}; }
+ (NSArray<LUDTypeAnnotation *> *)ludwiegMeta { 
	return @[
{{.annotations}}
	]; 
}

@end

{{.structures}}
`

const objcStructHeader = `{{.structures}}
@interface {{.name}} : NSObject <LUDSerializable>

{{.fields}}
@end`

const objcStructImplementation = `{{.structures}}
@implementation {{.name}}

+ (NSArray<LUDTypeAnnotation *> *)ludwiegMeta { 
	return @[
{{.annotations}}
	]; 
}

@end
`

const objcIntegrationSteps = `You just generated Objective-C sources. In order to use them you need to perform
a few tasks:

  1. Integrate Ludwieg framework with your project using {{.carthage}}. Download
     Carthage from https://github.com/Carthage/Carthage#installing-carthage
  2. Add Ludwieg to your {{.cartfile}}:

      {{.cartfileRequire}}
  
  3. Follow {{.carthage}} instructions: 
     https://github.com/Carthage/Carthage#getting-started
    
  4. Copy output files to your project.
  5. Before attempting deserializing data, you must register output packages.
     This operation must be performed only once, usually in your application's
     boot:

     {{.objcImport}}

     ...

     {{.objcRegister}}
`
